### ISSUE TITLE
I trying to solve one problem with import's

### ISSUE THREAD

**Issue by helderjnpinto** [pubkey/solidity-cli#3]
Related with this function: 
[link](https://github.com/pubkey/solidity-cli/blob/master/src/read-code.ts#L47)

The problem is: 
- need to remove duplicated import's, solc throw an error, 
- resolve path to node_modules like zeppelin is done right now!

Any ideas to solve duplicated problem ?

**Comment by pubkey** [comment]
Hi @helderjnpinto 
As mentioned [here](https://github.com/pubkey/solidity-cli/issues/2#issuecomment-443294511) we wait for [resolver-engine](https://github.com/resolver-engine/resolver-engine) to fix some problems and the use that module for the import resolutions. This should fix your problems. Also a PR will be welcomed.

**Comment by helderjnpinto** [comment]
@pubkey ok cool!
